#!/usr/bin/env python

import sys
sys.path.insert(0, "/srv/hacksense/lib")

import hacksense
import logging
import time

hacksense.setup_logging(redirect=True)

def callback(ch, method, properties, body):
    global conn

    topic = method.routing_key
    timestamp = properties.timestamp
    headers = properties.headers

    logging.info("%s %s %r" % (timestamp, topic, headers))

    if time.time()-timestamp > 10:
        # ignore old events
        # LCD max number of character displayed per line: x
        return

    if headers.get('authorized', False):
        conn.publish('doorbot.lcd.display', {'line1': 'Join us at' , 'line2': 'github.com/edinburghhacklab/hacksense', 'flash': 3})
    else:
        s = '%-20s' % (headers.get('uid', ''))
        conn.publish('doorbot.lcd.display', {'line1': 'Unknown Card', 'line2': s[2:18], 'flash': 5})

conn = hacksense.AMQPTopic()
conn.subscribe_callback("door.swipe", callback)
